#!/usr/local/bin/python

import sys

fname = "ergodox-config.url"
paths = [
    "/Users/david/.dotfiles/{}".format(fname),
    "/Users/david/Dropbox/{}".format(fname),
]

# -2 because now the file has the cloned_from, I think?
key = sys.argv[1].split("_")[-2]

content = "[InternetShortcut]\nURL=https://configure.ergodox-ez.com/ergodox-ez/layouts/{}/latest/0\n".format(
    key
)

for path in paths:
    with open(path, "w+") as f:
        f.write(content)
